language: ruby
bundler_args: --without guard
rvm:
  - "2.3.0"
  - ruby-head
script: "bundle exec rspec"
branches:
  only: master
notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
